### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by tihom** [manki/vetrivel-video-manager#1]
@manki 
Need details on how users are authenticated by REST API? For example we can  
have a header `X_USERNAME` with user's email. This is of course not secure as anyone  
can send this header with another user's email.

There are ways to use app engine for google account authentication as described [here](https://cloud.google.com/appengine/docs/python/users/#Python_User_authentication_in_Python).
However, that would tie us to app engine.

**Comment by manki** [comment]
Hi Mohit.

I was (still am) planning on using the App Engine Users API to authenticate users. It definitely ties us tightly to App Engine, but this will let us to launch our v1 quickly. I absolutely agree with you that the server cannot blindly accept the auth claims of the JavaScript code since it's easy to spoof.

If you don't want to code to App Engine-only API, maybe write a users module that in turn calls the App Engine API. (Sort of like having a VVM users API interface and multiple implementations; the first one would use App Engine's users API for ease of implementation.) Later, when we can, we can add more/different implementations to support other authentication approaches.

Does that sound like a reasonable approach?

**Comment by tihom** [comment]
@manki 

I am good with using App Engine. Auth can be made pluggable esp since back end is in Django where I have to write a custom class for authentication anyways.

Just to make sure I am going in the right direction with app engine auth. There would be no auth-header / info passed from the front end to back end.  Instead back end would use app engine API : `user = users.get_current_user()` to get user info. Let me know if this is not the right.

The above combined with XSRF should give us a secure implementation.

**Comment by manki** [comment]
Yes Mohit. That's precisely what I had in mind. JavaScript code won't pass any auth information to the server.
